Repository DJ-Java-Team/youmiteru-frontend, pull requests merged in 2024-01, with the labels that each got.

#2 Init Project
  .gitignore
  README.md
  frontend/.eslintrc.cjs
  frontend/index.html
  frontend/package.json
  frontend/src/App.scss
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: enhancement

#4 Organize a view of the project.
  frontend/src/assets/fonts/.gitkeep
  frontend/src/assets/icons/.gitkeep
  frontend/src/assets/images/.gitkeep
  frontend/src/assets/styles/.gitkeep
  frontend/src/components/.gitkeep
  frontend/src/constants/.gitkeep
  frontend/src/hooks/.gitkeep
  frontend/src/pages/.gitkeep
  frontend/src/types/.gitkeep
Labels: enhancement

#8 BugFix, Add License, Update Project
  LICENSE
  frontend/.eslintrc.cjs
  frontend/src/App.tsx
  frontend/src/main.tsx
Labels: bug, enhancement

#9 Create Routes to the pages. Add Routers to App.
  frontend/.eslintrc.cjs
  frontend/src/App.tsx
  frontend/src/constants/routes.ts
  frontend/src/main.tsx
Labels: enhancement

#13 Create Watch Button component:
  frontend/.eslintrc.cjs
  frontend/src/components/WatchButton/WatchButton.scss
  frontend/src/components/WatchButton/WatchButton.tsx
Labels: enhancement

#15 Feature/season title
  frontend/src/App.scss
  frontend/src/assets/styles/.gitkeep
  frontend/src/assets/styles/vars.scss
  frontend/src/components/.gitkeep
  frontend/src/components/SectionTitle/SectionTitle.scss
  frontend/src/components/SectionTitle/SectionTitle.tsx
  frontend/vite.config.ts
Labels: enhancement

#19 Feature/hook/dashboard data
  frontend/.env.dist
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/constants/.gitkeep
  frontend/src/constants/api.ts
  frontend/src/hooks/.gitkeep
  frontend/src/hooks/useDashBoardQuery.ts
  frontend/src/main.tsx
  frontend/src/types/.gitkeep
  frontend/src/types/Banner.ts
  frontend/src/types/DashBoard.ts
  frontend/src/types/Season.ts
Labels: enhancement

#17 Create SliderBanner component
  frontend/package.json
  frontend/src/assets/images/.gitkeep
  frontend/src/assets/images/left-arrow.svg
  frontend/src/assets/images/right-arrow.svg
  frontend/src/components/SliderBanner/SliderBanner.scss
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderButtons/NextArrow.tsx
  frontend/src/components/SliderButtons/PrevArrow.tsx
  frontend/src/components/SliderButtons/SliderButton.scss
  frontend/src/components/WatchButton/WatchButton.scss
  frontend/src/components/WatchButton/WatchButton.tsx
Labels: enhancement

#23 Navigation Bar component.
  frontend/src/App.scss
  frontend/src/App.tsx
  frontend/src/assets/icons/bookmark.svg
  frontend/src/assets/icons/catalog.svg
  frontend/src/assets/icons/home.svg
  frontend/src/assets/icons/search-icon.svg
  frontend/src/assets/icons/user_icon.svg
  frontend/src/assets/icons/website-logo.png
  frontend/src/assets/styles/vars.scss
  frontend/src/components/NavigationBar/NavBarBottom/NavBarBottom.scss
  frontend/src/components/NavigationBar/NavBarBottom/NavBarBottom.tsx
  frontend/src/components/NavigationBar/NavBarTop/NavBarTop.scss
  frontend/src/components/NavigationBar/NavBarTop/NavBarTop.tsx
  frontend/src/components/NavigationBar/NavigationBar.scss
  frontend/src/components/NavigationBar/NavigationBar.tsx
  frontend/src/components/SectionTitle/SectionTitle.tsx
  frontend/src/components/SliderButtons/NextArrow.tsx
  frontend/src/components/SliderButtons/PrevArrow.tsx
  frontend/src/constants/routes.ts
Labels: enhancement

#22 Feature/component/bg banner
  frontend/src/components/BgBanner/BgBanner.scss
  frontend/src/components/BgBanner/BgBanner.tsx
  frontend/src/components/SliderBanner/SliderBanner.scss
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderButtons/NextArrow.tsx
  frontend/src/components/SliderButtons/PrevArrow.tsx
  frontend/src/components/SliderButtons/SliderButton.scss
  frontend/src/components/WatchButton/WatchButton.scss
Labels: enhancement

#29 Update SectionTitle component.
  frontend/src/components/SectionTitle/SectionTitle.scss
Labels: bug
