Repository DJ-Java-Team/youmiteru-frontend, pull requests merged in 2024-03, with the labels that each got.

#56 Refactor SliderSeasons & SliderBanners
  .gitignore
  docker-compose.yml
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/assets/icons/glowing-star.svg
  frontend/src/assets/styles/vars.scss
  frontend/src/components/BgBanner/BgBanner.scss
  frontend/src/components/BgBanner/BgBanner.tsx
  frontend/src/components/NavigationBar/NavBarBottom/NavBarBottom.scss
  frontend/src/components/NavigationBar/NavBarTop/NavBarTop.scss
  frontend/src/components/SeasonDetails/SeasonDetails.scss
  frontend/src/components/SeasonDetails/SeasonDetails.tsx
  frontend/src/components/SliderBanner/SliderBanner.scss
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderSeasons/SliderSeasons.scss
  frontend/src/components/SliderSeasons/SliderSeasons.tsx
  frontend/src/components/WatchButton/WatchButton.scss
  frontend/src/components/WatchButton/WatchButton.tsx
  frontend/src/hooks/useDashBoardQuery.ts
  frontend/src/hooks/useSeasonDetailsQuery.ts
  frontend/src/pages/WatchAnime/WatchAnime.scss
  frontend/src/pages/WatchAnime/WatchAnime.tsx
  frontend/src/types/SliderSettings.ts
  ngrok-api.dist
Labels: bug fix

#55 Fix SliderSeasons and BgBanner
  frontend/src/components/SliderSeasons/SliderSeasons.scss
Labels: bug fix

#58 Set up and configure Tailwind CSS
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/src/App.scss
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: enhancement

#61 Feature/page/title
  frontend/src/App.tsx
  frontend/src/components/TitleInfo/TitleInfo.module.scss
  frontend/src/components/TitleInfo/TitleInfo.tsx
  frontend/src/components/TitleSeasons/TitleSeasons.module.scss
  frontend/src/components/TitleSeasons/TitleSeasons.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/useTitleQuery.ts
  frontend/src/pages/Title/Title.module.scss
  frontend/src/pages/Title/Title.tsx
  frontend/src/types/Title.ts
Labels: enhancement

#57 Feature/page/catalog
  .gitignore
  frontend/package.json
  frontend/src/components/AnimeList/AnimeList.scss
  frontend/src/components/AnimeList/AnimeList.tsx
  frontend/src/components/CatalogFilter/AgeRating/AgeRating.scss
  frontend/src/components/CatalogFilter/AgeRating/AgeRating.tsx
  frontend/src/components/CatalogFilter/CatalogFilter.scss
  frontend/src/components/CatalogFilter/CatalogFilter.tsx
  frontend/src/components/CatalogFilter/FetchAnimeButton/FetchAnimeButton.scss
  frontend/src/components/CatalogFilter/FetchAnimeButton/FetchAnimeButton.tsx
  frontend/src/components/CatalogFilter/Format/Format.scss
  frontend/src/components/CatalogFilter/Format/Format.tsx
  frontend/src/components/CatalogFilter/Genre/Genre.scss
  frontend/src/components/CatalogFilter/Genre/Genre.tsx
  frontend/src/components/CatalogFilter/Genre/GenreList/GenreList.scss
  frontend/src/components/CatalogFilter/Genre/GenreList/GenreList.tsx
  frontend/src/components/CatalogFilter/ReleaseYear/ReleaseYear.scss
  frontend/src/components/CatalogFilter/ReleaseYear/ReleaseYear.tsx
  frontend/src/components/CatalogFilter/ResetButton/ResetButton.scss
  frontend/src/components/CatalogFilter/ResetButton/ResetButton.tsx
  frontend/src/components/CatalogFilter/Season/Season.scss
  frontend/src/components/CatalogFilter/Season/Season.tsx
  frontend/src/components/CatalogFilter/State/State.scss
  frontend/src/components/CatalogFilter/State/State.tsx
  frontend/src/components/CatalogFilter/Year/Year.scss
  frontend/src/components/CatalogFilter/Year/Year.tsx
  frontend/src/constants/genre.ts
  frontend/src/hooks/useCatalogQuery.ts
  frontend/src/pages/Catalog/Catalog.scss
  frontend/src/pages/Catalog/Catalog.tsx
  frontend/src/types/Catalog.ts
Labels: enhancement

#62 Add season-details component to watch-season page.
  docker-compose.yml
  fake-api/.dockerignore
  fake-api/Dockerfile
  fake-api/db.json
  fake-api/package.json
  frontend/.env.dist
  frontend/package.json
  frontend/src/App.scss
  frontend/src/assets/icons/bookmark1.svg
  frontend/src/assets/styles/vars.scss
  frontend/src/components/BgBanner/BgBanner.tsx
  frontend/src/components/BookmarkIcon.tsx
  frontend/src/components/SeasonDetails.tsx
  frontend/src/components/SeasonDetails/SeasonDetails.scss
  frontend/src/components/SeasonDetails/SeasonDetails.tsx
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderSeasons/SliderSeasons.tsx
  frontend/src/hooks/useDashBoardQuery.ts
  frontend/src/hooks/useSeasonDetailsQuery.ts
  frontend/src/main.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/WatchAnime/WatchAnime.tsx
  frontend/src/types/Banner.ts
  frontend/src/types/DashBoard.ts
  frontend/src/types/Season.ts
  frontend/src/types/SeasonDetails.ts
  frontend/tailwind.config.ts
  ngrok-api.dist
  ngrok-example.dist
Labels: enhancement

#63 Update README.md
  README.md
Labels: documentation

#67 Create RateSeason component
  frontend/package.json
  frontend/src/components/RateSeason.tsx
  frontend/src/components/SeasonDetails.tsx
  frontend/src/pages/WatchAnime/WatchAnime.tsx
Labels: enhancement

#68 Create AnimeDetailsTabs component
  frontend/src/components/AnimeDetailsTabs/AnimeDetailsTabs.tsx
  frontend/src/components/AnimeDetailsTabs/ChronologySeason.tsx
  frontend/src/components/AnimeDetailsTabs/ScrollableDescription.tsx
  frontend/src/pages/WatchAnime/WatchAnime.tsx
Labels: enhancement
