Repository DJ-Java-Team/youmiteru-frontend, pull requests merged in 2024-02, with the labels that each got.

#27 Bug fix/component/bg banner
  frontend/src/assets/icons/left-arrow.svg
  frontend/src/assets/icons/right-arrow.svg
  frontend/src/components/BgBanner/BgBanner.scss
  frontend/src/components/BgBanner/BgBanner.tsx
  frontend/src/components/SliderBanner/SliderBanner.scss
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderButtons/NextArrow.tsx
  frontend/src/components/SliderButtons/PrevArrow.tsx
  frontend/src/components/SliderButtons/SliderButton.scss
Labels: bug

#30 Feature/component/footer
  frontend/src/App.scss
  frontend/src/assets/icons/discord-logo.png
  frontend/src/assets/icons/telegram-logo.png
  frontend/src/assets/icons/vk-logo.png
  frontend/src/components/BgBanner/BgBanner.scss
  frontend/src/components/Footer/Footer.scss
  frontend/src/components/Footer/Footer.tsx
  frontend/src/constants/misc.ts
  frontend/src/constants/routes.ts
Labels: enhancement

#21 Feature/component/slider seasons
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/icons/left-arrow-season.svg
  frontend/src/assets/icons/left-arrow.svg
  frontend/src/assets/icons/right-arrow-season.svg
  frontend/src/assets/icons/right-arrow.svg
  frontend/src/components/BannerArrows/NextArrow.tsx
  frontend/src/components/BannerArrows/PrevArrow.tsx
  frontend/src/components/BannerArrows/SliderButton.scss
  frontend/src/components/SeasonArrows/NextArrow.tsx
  frontend/src/components/SeasonArrows/PrevArrow.tsx
  frontend/src/components/SeasonArrows/SeasonArrows.scss
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderSeasons/SliderSeasons.scss
  frontend/src/components/SliderSeasons/SliderSeasons.tsx
  frontend/src/types/Banner.ts
  frontend/src/types/Season.ts
Labels: enhancement

#32 Create Home Page and refactor styles for arrows.
  frontend/src/App.tsx
  frontend/src/components/BannerArrows/SliderButton.scss
  frontend/src/components/BgBanner/BgBanner.tsx
  frontend/src/components/SeasonArrows/SeasonArrows.scss
  frontend/src/components/SliderSeasons/SliderSeasons.scss
  frontend/src/components/SliderSeasons/SliderSeasons.tsx
  frontend/src/components/WatchButton/WatchButton.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/Home/Home.scss
  frontend/src/pages/Home/Home.tsx
Labels: bug, enhancement

#33 Bug fix/page/home
  frontend/src/components/BannerArrows/SliderButton.scss
  frontend/src/components/BgBanner/BgBanner.scss
  frontend/src/components/Footer/Footer.scss
  frontend/src/components/NavigationBar/NavBarTop/NavBarTop.scss
  frontend/src/components/SeasonArrows/SeasonArrows.scss
  frontend/src/components/SectionTitle/SectionTitle.scss
  frontend/src/components/SliderBanner/SliderBanner.scss
  frontend/src/components/SliderBanner/SliderBanner.tsx
  frontend/src/components/SliderSeasons/SliderSeasons.scss
  frontend/src/components/SliderSeasons/SliderSeasons.tsx
  frontend/src/components/WatchButton/WatchButton.scss
  frontend/src/components/WatchButton/WatchButton.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/types/SliderSettings.ts
Labels: bug fix

#37 Refactor DashBoard type and update getting data.
  frontend/src/pages/Home/Home.tsx
  frontend/src/types/DashBoard.ts
Labels: bug fix

#35 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  frontend/src/types/DashBoard.ts
Labels: enhancement

#38 Create Docker setup configuration
  .gitignore
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/package.json
  frontend/vite.config.ts
  ngrok-example.dist
Labels: enhancement

#40 Initial Catalog page.
  frontend/src/App.tsx
  frontend/src/pages/Catalog/Catalog.scss
  frontend/src/pages/Catalog/Catalog.tsx
Labels: enhancement

#49 Create SeasonDetail hook.
  frontend/src/hooks/useSeasonDetailsQuery.ts
  frontend/src/types/SeasonDetails.ts
Labels: enhancement

#51 Create fake-api
  docker-compose.yml
  fake-api/.dockerignore
  fake-api/Dockerfile
  fake-api/db.json
  fake-api/package.json
Labels: enhancement, bug fix

#53 Feature/page/login page
  frontend/src/App.tsx
  frontend/src/assets/icons/discord-login-logo.svg
  frontend/src/assets/icons/gogle-logo.svg
  frontend/src/assets/icons/login-page-bg.png
  frontend/src/assets/icons/vk-logo.svg
  frontend/src/assets/icons/yandex-logo.svg
  frontend/src/components/AuthButton/AuthButtons.scss
  frontend/src/components/AuthButton/AuthButtons.tsx
  frontend/src/components/AuthButton/DiscordAuthButton/DiscordAuthButton.scss
  frontend/src/components/AuthButton/DiscordAuthButton/DiscordAuthButton.tsx
  frontend/src/components/AuthButton/GoogleAuthButton/GoogleAuthButton.scss
  frontend/src/components/AuthButton/GoogleAuthButton/GoogleAuthButton.tsx
  frontend/src/components/AuthButton/VkAuthButton/VkAuthButton.scss
  frontend/src/components/AuthButton/VkAuthButton/VkAuthButton.tsx
  frontend/src/components/AuthButton/YandexAuthButton/YandexAuthButton.scss
  frontend/src/components/AuthButton/YandexAuthButton/YandexAuthButton.tsx
  frontend/src/components/NavigationBar/NavBarTop/NavBarTop.scss
  frontend/src/pages/Login/Login.scss
  frontend/src/pages/Login/Login.tsx
Labels: enhancement
